services:
  # watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower
  #   command: --interval 5
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_LABEL_ENABLE=true
  #     - WATCHTOWER_LABEL_FILTER=watchtower
  #   restart: always
  # nextapp:
  #   container_name: nextapp
  #   image: nextapp:1.0.0
  #   build:
  #     context: ./frontend
  #     dockerfile: next.dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   #depends_on:
  #     #- goapp
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgresql://project_two_siem_user:aziYylQ23YNm9ML6Hkyjny9zSt76AbPB@dpg-cvcgb61c1ekc73equm90-a.oregon-postgres.render.com/project_two_siem'
    ports:
      - '8000:8000'

volumes:
  pgdata: {}
